serverURL: "localhost:8080"
allowedOrigins:
  - "http://localhost:3000" # Next.js dev server
  - "http://localhost:8080" # Go Web server once built

destinationRule: "http-echo.infra.svc.cluster.local"
virtualServiceNamespace: "infra"
virtualServiceHosts:
  - "domain.example"
